# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-11T16:03:04Z"
  labels:
    app: nombreContainer
  name: nombreContainer
spec:
  containers:
  - args:
    - apache2-foreground
    command:
    - docker-php-entrypoint
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_VERSION
      value: 7.4.16
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.4.16.tar.xz
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    - name: GPG_KEYS
      value: 42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.4.16.tar.xz.asc
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: PHP_EXTRA_BUILD_DEPS
      value: apache2-dev
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --with-apxs2 --disable-cgi
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: PHP_SHA256
      value: 1c16cefaf88ded4c92eed6a8a41eb682bb2ef42429deb55f1c4ba159053fb98b
    image: localhost/php-mysql-apache
    name: apache
    ports:
    - containerPort: 80
      hostPort: 8000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/www/html
      name: home-ubuntu-www-html-wordpress
    workingDir: /var/www/html
  - args:
    - mysqld
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: MYSQL_PASSWORD
      value: admin
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: admin
    - name: MARIADB_MAJOR
      value: "10.5"
    - name: MARIADB_VERSION
      value: 1:10.5.9+maria~focal
    - name: GPG_KEYS
      value: 177F4010FE56CA3336300305F1656F24C74CD1D8
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: GOSU_VERSION
      value: "1.12"
    image: docker.io/library/mariadb
    name: mariadb
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: home-ubuntu-data-mariadb
    workingDir: /
  dnsConfig: {}
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/ubuntu/www-html/wordpress
      type: Directory
    name: home-ubuntu-www-html-wordpress
  - hostPath:
      path: /home/ubuntu/data-mariadb
      type: Directory
    name: home-ubuntu-data-mariadb
status: {}
